kind: pipeline
type: docker
name: deploy

trigger:
  branch:
    - main
  ref:
    - refs/tags/*

steps:
  - name: set-version-number
    image: alpine
    commands:
      - grep -rl 0.0.0-dev trunk | xargs sed -i 's/0.0.0-dev/${DRONE_TAG}/g'

  - name: build-composer
    image: composer
    commands:
      - composer install --ignore-platform-reqs

  - name: create-zip
    image: javieraviles/zip
    commands:
      - mv trunk woocommerce-zaver-checkout
      - zip -r woocommerce-zaver-checkout-latest.zip woocommerce-zaver-checkout
      - cp woocommerce-zaver-checkout-latest.zip woocommerce-zaver-checkout-${DRONE_TAG}.zip

  - name: upload-to-s3
    image: plugins/s3
    settings:
      bucket: wm-static
      access_key:
        from_secret: s3_key
      secret_key:
        from_secret: s3_secret
      source: woocommerce-zaver-checkout-*.zip
      target: /zaver/woocommerce-zaver-checkout
      endpoint: https://fra1.digitaloceanspaces.com
      acl: public-read
  
  - name: publish-to-wordpress-org
    image: profiprog/svn
    environment:
      SVN_USERNAME:
        from_secret: svn_username
      SVN_PASSWORD:
        from_secret: svn_password
    commands:
      - apk add rsync
      - mkdir svn-repo
      - svn co https://plugins.svn.wordpress.org/zaver-checkout-for-woocommerce svn-repo --depth empty
      - svn mkdir --parents svn-repo/assets svn-repo/trunk svn-repo/tags
      - rsync -ar --delete assets svn-repo/assets
      - rsync -ar --delete trunk svn-repo/trunk
      - cd svn-repo
      - svn add assets/* trunk/*
      - svn cp trunk tags/${DRONE_TAG}
      - svn ci -m 'Version ${DRONE_TAG}' --username ${SVN_USERNAME} --password ${SVN_PASSWORD}