<?php
/**
 * The payment processor class.
 *
 * @package ZCO/Classes
 */

namespace Zaver;

use Exception;
use WC_Order;
use KrokedilZCODeps\Zaver\SDK\Config\PaymentStatus;
use KrokedilZCODeps\Zaver\SDK\Object\PaymentStatusResponse;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Payment_Processor
 *
 * Handles the payment processing.
 */
class Payment_Processor {

	/**
	 * Process a payment for the given order.
	 *
	 * @param WC_Order $order The order to process the payment for.
	 * @return void
	 */
	public static function process( $order ) {
		$payment = Classes\Helpers\Order::create( $order );

		do_action( 'zco_before_process_payment', $payment, $order );
		$response = Plugin::gateway()->api()->createPayment( $payment );
		ZCO()->logger()->info(
			'Created Zaver payment request',
			array(
				'payload'   => $payment,
				'response'  => $response,
				'orderId'   => $order->get_id(),
				'paymentId' => $response->getPaymentId(),
			)
		);

		$token = $response->getToken();

		$settings         = get_option( 'woocommerce_zaver_checkout_settings', array() );
		$separate_methods = wc_string_to_bool( $settings['separate_methods'] ?? 'no' );
		if ( $separate_methods ) {
			$selected_payment_method   = $order->get_payment_method();
			$available_payment_methods = $response->getSpecificPaymentMethodData();
			foreach ( $available_payment_methods as $payment_method ) {
				$title = strtolower( $payment_method['paymentMethod'] );
				if ( strpos( $selected_payment_method, $title ) !== false ) {
					$order->update_meta_data( '_zaver_payment_method', $payment_method['paymentMethod'] );
					$order->update_meta_data( '_zaver_payment_link', $payment_method['paymentLink'] );
					$token = $payment_method['checkoutToken'];
					break;
				}
			}
		} else {
			$order->update_meta_data( '_zaver_payment_link', $response->getPaymentLink() );
		}

		$order->update_meta_data(
			'_zaver_payment',
			array(
				'id'              => $response->getPaymentId(),
				'token'           => $token,
				'tokenValidUntil' => $response->getValidUntil(),
			)
		);

		$order->save_meta_data();

		// Save all line item IDs generated by Zaver.
		foreach ( $response->getLineItems() as $item ) {
			$meta = $item->getMerchantMetadata();

			if ( isset( $meta['orderItemId'] ) ) {
				wc_add_order_item_meta( $meta['orderItemId'], '_zaver_line_item_id', $item->getId(), true );
			}
		}

		do_action( 'zco_after_process_payment', $payment, $order, $response );
	}

	/**
	 * Handle the response from Zaver.
	 *
	 * @throws Exception If the order key is invalid, the payment ID is missing, or the payment ID does not match.
	 *
	 * @param WC_Order                   $order The order to handle the response for.
	 * @param PaymentStatusResponse|null $payment_status The payment status response.
	 * @param bool                       $redirect Whether to redirect the user.
	 * @return void
	 */
	public static function handle_response( $order, $payment_status = null, $redirect = true ) {

		// TODO: I believe what they meant here is to check for if $order->get_date_paid() is not null.
		// Ignore orders that are already paid.
		if ( ! $order->needs_payment() ) {
			return;
		}

		// Ensure that the order key is correct.
		$key = filter_input( INPUT_GET, 'key', FILTER_SANITIZE_SPECIAL_CHARS );
		if ( empty( $key ) || ! hash_equals( $order->get_order_key(), $key ) ) {
			throw new Exception( 'Invalid order key' );
		}

		$payment = $order->get_meta( '_zaver_payment' );
		if ( ! isset( $payment['id'] ) ) {
			throw new Exception( 'Missing payment ID on order' );
		}

		if ( null === $payment_status ) {
			$payment_status = Plugin::gateway()->api()->getPaymentStatus( $payment['id'] );
			ZCO()->logger()->info(
				'Fetched payment status from Zaver',
				array(
					'payload'  => $payment['id'],
					'response' => $payment_status,
					'orderId'  => $order->get_id(),
				)
			);
		} elseif ( $payment_status->getPaymentId() !== $payment['id'] ) {
			throw new Exception( 'Mismatching payment ID' );
		}

		do_action( 'zco_process_payment_handle_response', $order, $payment_status, $redirect );

		switch ( $payment_status->getPaymentStatus() ) {
			case PaymentStatus::SETTLED:
				// translators: %s is the payment ID.
				$order->add_order_note( sprintf( __( 'Successful payment with Zaver - payment ID: %s', 'zco' ), $payment_status->getPaymentId() ) );
				$order->payment_complete( $payment_status->getPaymentId() );
				ZCO()->logger()->info(
					'Successful payment with Zaver',
					array(
						'orderId'   => $order->get_id(),
						'paymentId' => $payment_status->getPaymentId(),
					)
				);
				break;

			case PaymentStatus::CANCELLED:
				ZCO()->logger()->info(
					'Zaver Payment was cancelled',
					array(
						'orderId'   => $order->get_id(),
						'paymentId' => $payment_status->getPaymentId(),
					)
				);

				if ( $redirect ) {
					wp_safe_redirect( $order->get_cancel_order_url() );
					exit;
				}

				$order->update_status( 'cancelled', __( 'Zaver payment was cancelled - cancelling order', 'zco' ) );
				break;

			case PaymentStatus::CREATED:
				ZCO()->logger()->debug(
					'Zaver Payment is still in CREATED state',
					array(
						'orderId'   => $order->get_id(),
						'paymentId' => $payment_status->getPaymentId(),
					)
				);

				if ( $redirect ) {
					wp_safe_redirect( $order->get_checkout_payment_url( true ) );
					exit;
				}

				// Do nothing.
				break;
			case PaymentStatus::PENDING_CONFIRMATION:
				$order->update_status( 'on-hold', __( 'Zaver Payment is pending confirmation', 'zco' ) );
				ZCO()->logger()->info(
					'Zaver Payment is pending confirmation',
					array(
						'orderId'   => $order->get_id(),
						'paymentId' => $payment_status->getPaymentId(),
					)
				);
				break;
			default:
				ZCO()->logger()->error(
					'Received unhandled payment status from Zaver',
					array(
						'orderId'       => $order->get_id(),
						'paymentId'     => $payment_status->getPaymentId(),
						'paymentStatus' => $payment_status->getPaymentStatus(),
					)
				);
				break;
		}
	}
}
